### ISSUE TITLE
None

### ISSUE THREAD

**Issue by lccodes** [anjuthomas/nodeOIDCMsg#1]
https://github.com/anjuthomas/nodeOIDCMsg/blob/63d205e10c157f94e8c77451351559c460a92f81/Node%20JWT/verify.js#L65

Doesn't this default the algo to none?

**Comment by anjuthomas** [comment]
It looks like it signs with the default algorithm HS256 but verifies with the algorithm None only if there is no signature and no algorithm specified. I thought all JWT libraries should support none algorithm, for no signature at all.  If we specify none as algorithm in the header and leave out the signature, some implementations may accept our JWT as correctly signed. If you are passing a secret signing key to the method that verifies the signature and the signature algorithm is set to ‘none’, it should fail verification. In this case if we don't have a signature and the algorithm is set to 'none' by default, does this lead to any security hole?

**Comment by lccodes** [comment]
We should support none, but I don't think we should turn it on by default unless the developer has explicitly enabled it. If this functionality only occurs once the developer has configured None to work then we're fine otherwise I think this might be a hole.

**Comment by anjuthomas** [comment]
Yes I will be working on adding the functionality where the developer has to explicitly enable it

**Comment by anjuthomas** [comment]
The none algorithm check and the setting to explicitly enable it has been added.
