### ISSUE TITLE
First Paragraph

### ISSUE THREAD

**Issue by lccodes** [anjuthomas/nodeOIDCMsg#10]
[Reference](https://github.com/anjuthomas/nodeOIDCMsg#what-is-the-message-class)

Can you fix the grammar in this paragraph and make it clearer? I think I get what you're saying, but I'm honestly not sure.

**Comment by anjuthomas** [comment]
Sorry about that. I have made a few changes to the doc. Does it sound better now?

**Comment by lccodes** [comment]
I don't see a change, did you push? For example:

"information are"
"number of method"

**Comment by anjuthomas** [comment]
Oops I thought you were referring to another section. I have the change to the message section as well.
