### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by lccodes** [anjuthomas/nodeOIDCMsg#11]
[Reference](https://github.com/anjuthomas/nodeOIDCMsg#options)

Why is issuer listed as optional here?

**Comment by anjuthomas** [comment]
The  original 0auth project had two ways you can add issuer, one in the payload itself and the other as part of the options. I kept the same structure as the original 0Auth project. I have a check where if the user specifies a duplicate value in both the payload and in options, it throws an error, so the user cannot add an issuer in both the payload and options. 

Along with the issuer, there are couple of other options that can be provided that are not required :
algorithms: List of strings with the names of the allowed algorithms. For instance, ["HS256", "HS384"].
audience: if you want to check audience (aud), provide a value here. The audience can be checked against a string, a regular expression or a list of strings and/or regular expressions. Eg: "urn:foo", /urn:f[o]{2}/, [/urn:f[o]{2}/, "urn:bar"]
issuer (optional): string or array of strings of valid values for the iss field.
ignoreExpiration: if true do not validate the expiration of the token.
ignoreNotBefore...
subject: if you want to check subject (sub), provide a value here
clockTolerance: number of seconds to tolerate when checking the nbf and exp claims, to deal with small clock differences among different servers
maxAge: the maximum allowed age for tokens to still be valid. It is expressed in seconds or a string describing a time span zeit/ms. Eg: 1000, "2 days", "10h", "7d".
clockTimestamp: the time in seconds that should be used as the current time for all necessary comparisons.

**Comment by lccodes** [comment]
What is "the options"? Where does that live in a JWT?

**Comment by anjuthomas** [comment]
Options are other inputs or additional information that might be needed and are not part of the payload, for ex : 'algorithm'. Other options can be passed as in as the fourth parameter to token profile’s fromJWT method. It is an existing feature in the 0Auth project.

 BasicIdToken.prototype.fromJWT = function(signedJWT, secretOrPrivateKey, claimsToVerify, options, callback)
