### ISSUE TITLE
Input Clarification

### ISSUE THREAD

**Issue by lccodes** [anjuthomas/nodeOIDCMsg#13]
[Reference](https://github.com/anjuthomas/nodeOIDCMsg#options)

I get that the first input to fromJWT is the signed JWT that will be decoded, the second is the key, the third is the claims to verify, but what is the fourth?

**Comment by anjuthomas** [comment]
If you look at the callbacks section in the very bottom of the documentation, I have added the method signatures for the fromJwt and toJwt method. Hopefully this clarifies the parameters. in this case the fourth is the 'Options' mentioned in the doc, which is optional/ additional information that can be added but not as part of the payload. Both the options and the callback (fifth parameter) are not required parameters when calling fromJwt. 
 
BasicIdToken.prototype.fromJWT = function(signedJWT, secretOrPrivateKey, claimsToVerify, options, callback)

**Comment by lccodes** [comment]
Okay, can you flesh that out in the Readme a little more? Particularly the section headers because things like "Options" confused me and made it unclear what options they were for. 

Functionality sounds good though.

**Comment by anjuthomas** [comment]
Yeah, I agree. Will make the change for Options. Btw, what change did you want me to make to the section headers? Can you please clarify which section headers you were referring to?

**Comment by anjuthomas** [comment]
Done
