### ISSUE TITLE
Nonstandard Claims Questions

### ISSUE THREAD

**Issue by lccodes** [anjuthomas/nodeOIDCMsg#14]
What happens when a nonstandard claim such as aud is supplied to the verifier, but the decodedJWT doesn't include aud? 

Why is clock timestamp passed in as a parameter rather than just fetched from the system?

**Comment by anjuthomas** [comment]
If an aud is provided in the verifier but the decoded jWT doesn't include aud, it just ignores it. However if the aud is provided in the decoded jwt as well, it checks to see if it matches with the provided verification claim.

Clock timestamp was one of the existing options in the original OAuth project. This allows the user to provide any date and time and not just the current. In the backend, it fetches the clockTimestamp from the system if it is not provided : 

     var clockTimestamp = otherOptions.clockTimestamp || Math.floor(Date.now() / 1000);

**Comment by lccodes** [comment]
1) Let's discuss with the group to confirm that is the desired behavior. Part of me thinks it should error, part me of thinks it should be ignored.

2) Ah, that seems great. Maybe just document that more clearly.

**Comment by anjuthomas** [comment]
1. Sounds good. I was torn as well regarding whether we should ignore it or raise an error. 

2. I will add it to the documentation in order clarify this :)

**Comment by anjuthomas** [comment]
Done.
