### ISSUE TITLE
Unclear

### ISSUE THREAD

**Issue by rohe** [anjuthomas/nodeOIDCMsg#15]
In the readme file you have:
"While sending request and responses, it must be possible to serialize the information to a format that can be transmitted over-the-wire."

Should possibly be something along these lines:

When sending request, it must be possible to serialize the information to a format that can be transmitted over-the-wire. Likewise, when receiving responses it must be possible to de-serialize these into an internal representation.

You get the drift ?

**Comment by anjuthomas** [comment]
Oops i forgot to add the deserialize keyword. Good catch. I will make the change.

**Comment by anjuthomas** [comment]
Done
