### ISSUE TITLE
BasicIdToken

### ISSUE THREAD

**Issue by rohe** [anjuthomas/nodeOIDCMsg#16]
I think the name BasicIdToken should be replaced with basicJsonWebToken (or basicJWT).

The reason is that an IdToken is not a security token and really we want to be 
as general as possible.

**Comment by anjuthomas** [comment]
Makes sense. I will make the change. Might take some time as I have to change the names on all the tests and files :P  Hopefully the replace feature is useful here.

**Comment by anjuthomas** [comment]
Done. Will make the change in the code as well.
