### ISSUE TITLE
Checking agains multiple audiences, questionable

### ISSUE THREAD

**Issue by rohe** [anjuthomas/nodeOIDCMsg#2]
https://github.com/anjuthomas/nodeOIDCMsg/blob/9aa91cf49c50ce8b4167ae9196cee3c31963401c/Node-JWT%20Tests/claims-test.js#L47

This might be nit picking but any receiver of a JWT should just have one identity (for the channel on which it received the JWT) not several.

There are a number of similar tests that should be removed if this one is.

**Comment by anjuthomas** [comment]
I have disabled multiple identities. Will upload the latest changes after making other changes.

**Comment by anjuthomas** [comment]
Fixed in the latest version
