### ISSUE TITLE
Signing with incorrect audience

### ISSUE THREAD

**Issue by rohe** [anjuthomas/nodeOIDCMsg#3]
https://github.com/anjuthomas/nodeOIDCMsg/blob/9aa91cf49c50ce8b4167ae9196cee3c31963401c/Node-JWT%20Tests/claims-test.js#L64

1) This test is for incorrect audience when checking. I see no test for having an incorrect audience when signing or ..

2) Audience is defined to be StringOrURI. Assuming that the audience value/-s is/are correct then
it doesn't matter if the audience provided when checking is syntactically correct. If it matches it does if not it doesn't.
So adding a check to see if the value provided is correct seems like overkill.

**Comment by anjuthomas** [comment]
Good point. I will add that test.

**Comment by anjuthomas** [comment]
Lee said that this might need further discussion. I have added the test.
