### ISSUE TITLE
'sub' and 'jti' are what they are.

### ISSUE THREAD

**Issue by rohe** [anjuthomas/nodeOIDCMsg#4]
https://github.com/anjuthomas/nodeOIDCMsg/blob/9aa91cf49c50ce8b4167ae9196cee3c31963401c/Node-JWT%20Tests/claims-test.js#L224

The values of 'sub' and 'jti' are what they are. You as a recipient of a JWT can't question their values.
You can only check that the type of the values are correct (both should be strings) not their content.

**Comment by anjuthomas** [comment]
I will change the test to verify the type and not the content.
