### ISSUE TITLE
Don't understand the logic

### ISSUE THREAD

**Issue by rohe** [anjuthomas/nodeOIDCMsg#5]
https://github.com/anjuthomas/nodeOIDCMsg/blob/9aa91cf49c50ce8b4167ae9196cee3c31963401c/Node-JWT%20Tests/claims-test.js#L296

Why is { nonstandardClaim: 'urn:foo' } included when doing verification ? 
Seems like you have to specify what the non standard claims can be. Right ?

**Comment by anjuthomas** [comment]
Good catch. I have enabled the non standard claim verification only for the ones that are known. Will upload the latest version with the other changes.

**Comment by anjuthomas** [comment]
Added the fix for non standard verification in the latest github version
