### ISSUE TITLE
No tests for exposing maps of standard/non-standard claims

### ISSUE THREAD

**Issue by rohe** [anjuthomas/nodeOIDCMsg#6]
This goes back to Lee's comment on the Functionality Table:

"Exposing map of all claims and map of non-standard claims should be common to all libraries. Whether to expose a map-like interface on the messages themselves should be based on whether it makes sense for the language."

**Comment by anjuthomas** [comment]
I will add the test for exposing maps in the message layer after further research about whether the message layer is necessary for the javascript version.
