### ISSUE TITLE
Top Level Folders

### ISSUE THREAD

**Issue by lccodes** [anjuthomas/nodeOIDCMsg#8]
I don't understand the separation right now. What does each handle and why do they need to be separate? If it's not please make a better structure. if it is then please document that.  

This applies recursively to sub folders. I'm using commits to find relevant code, but generally don't understand how to navigate the library.

**Comment by anjuthomas** [comment]
I agree, this was on my todo list. The original auth0 library was not very well structured, commented, or modularized before. I will work on improving the structure and modularizing it so its easier to understand the flow :)

**Comment by anjuthomas** [comment]
Done. I have uploaded to git. Please review and let me know if you would like me to make any changes.
